package main

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"

	"iple-backend/internal/config"     // <-- แทนที่ your_module_path
	"iple-backend/internal/database"   // <-- แทนที่ your_module_path
	"iple-backend/internal/middleware" //<-- แทนที่ your_module_path
	"iple-backend/internal/routes"     // <-- แทนที่ your_module_path
	"iple-backend/internal/utils"      // <-- แทนที่ your_module_path

	// Import docs generated by Swag CLI (หลังจากรัน swag init)
	_ "iple-backend/docs" // <-- แทนที่ your_module_path

	"github.com/go-playground/validator"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/helmet"

	// "github.com/gofiber/fiber/v2/middleware/logger" // ใช้ Custom Logger แทน
	"github.com/gofiber/fiber/v2/middleware/recover"
	fiberSwagger "github.com/swaggo/fiber-swagger"
)

// @title           IPLE LMS Core API
// @version         1.0
// @description     API endpoints for the Core LMS Module of IPLE. Provides user management, course handling, enrollments, basic activities, and parent portal access.
// @termsOfService  http://swagger.io/terms/
// @contact.name   IPLE Dev Team
// @contact.url    https://github.com/your-org/iple-backend // <--- แก้ไข URL
// @contact.email  dev@example.com // <--- แก้ไข Email
// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html
// @host            localhost:8080 // Adjust for deployment
// @BasePath        /api/v1
// @schemes         http https
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.
func main() {
	// --- 1. Load Configuration ---
	config.LoadConfig()

	// --- Setup Structured Logger (slog) ---
	logLevel := new(slog.LevelVar)
	switch config.Env.LogLevel {
	case "debug":
		logLevel.Set(slog.LevelDebug)
	case "warn":
		logLevel.Set(slog.LevelWarn)
	case "error":
		logLevel.Set(slog.LevelError)
	default:
		logLevel.Set(slog.LevelInfo)
	}
	// ใช้ JSON handler สำหรับ Production/Logs ที่ต้องการ Parse ง่าย
	// ใช้ Text handler สำหรับ Local development ถ้าต้องการอ่านง่ายขึ้น
	var handler slog.Handler = slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{Level: logLevel})
	if os.Getenv("ENV") != "production" {
		handler = slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{Level: logLevel})
	}
	appLogger := slog.New(handler)
	slog.SetDefault(appLogger)
	slog.Info("Configuration loaded", "port", config.Env.Port, "log_level", config.Env.LogLevel)

	// --- Initialize JWT Helper (อ่าน Secret Key) ---
	if err := utils.InitJWT(); err != nil { // สร้างฟังก์ชัน InitJWT ใน utils
		slog.Error("Failed to initialize JWT", "error", err)
		os.Exit(1)
	}
	slog.Info("JWT helper initialized")


	// --- 2. Connect to Database ---
	database.ConnectDB() // ควร Log Fatal ภายใน ConnectDB ถ้าเชื่อมต่อไม่ได้
	slog.Info("Database connection established")

	// --- 3. Initialize Fiber App with Custom Error Handler ---
	app := fiber.New(fiber.Config{
		ErrorHandler: func(ctx *fiber.Ctx, err error) error {
			code := fiber.StatusInternalServerError
			resp := utils.NewErrorResponse(code, "INTERNAL_ERROR", "Internal Server Error") // ใช้ Helper

			var e *fiber.Error
			var valErrs validator.ValidationErrors // ตรวจสอบ Validation Error โดยเฉพาะ

			if errors.As(err, &e) {
				// ใช้ Status Code จาก Fiber Error
				code = e.Code
				resp = utils.NewErrorResponse(code, fmt.Sprintf("FIBER_%d", code), e.Message)
			} else if errors.As(err, &valErrs) {
                // จัดการ Validation Errors จาก go-playground/validator
                code = fiber.StatusBadRequest
                 details := utils.FormatValidationErrors(valErrs) // Helper ใหม่สำหรับ format validation errors
                 resp = utils.NewValidationErrorResponse(details) // ใช้ DTO แยกสำหรับ validation
			} else {
				// Log the original unexpected error for internal tracking
				slog.Error("Unhandled error",
					"path", ctx.Path(),
					"error", err.Error(),
					"request_id", ctx.Locals(middleware.RequestIDKey), // ใช้ค่าจาก middleware
				)
			}

			// Return JSON error response
			return ctx.Status(code).JSON(resp)
		},
	})

	// --- 4. Setup Middleware (ลำดับสำคัญ!) ---
	app.Use(recover.New(recover.Config{EnableStackTrace: true})) // 1. Recovery (ต้องมาก่อน Logger/RequestID เพื่อดัก Panic ได้หมด)
	app.Use(middleware.RequestID())                             // 2. Request ID
	app.Use(middleware.StructuredLogger(slog.Default()))         // 3. Structured Logger (ใช้ Default logger ที่ตั้งค่าไว้)
	app.Use(cors.New(cors.Config{                               // 4. CORS
		// **สำคัญ:** แก้ไขสำหรับ Production
		AllowOrigins:     config.GetAllowedOrigins(), // สร้างฟังก์ชันใน config เพื่ออ่านจาก Env Var เช่น "http://localhost:3000,https://your-prod-domain.com"
		AllowHeaders:     "Origin, Content-Type, Accept, Authorization, X-Request-ID", // เพิ่ม X-Request-ID
		AllowMethods:     "GET,POST,PUT,DELETE,PATCH,OPTIONS",
		AllowCredentials: true,
	}))
	app.Use(helmet.New()) // 5. Security Headers

	// --- 5. Setup Swagger ---
	// ตรวจสอบว่า Environment ไม่ใช่ Production ก่อนเปิด Swagger? (Optional)
	// if os.Getenv("ENV") != "production" {
		app.Get("/swagger/*", fiberSwagger.WrapHandler)
		slog.Info("Swagger UI available at /swagger/index.html")
	// }

	// --- 6. Setup Application Routes ---
	routes.SetupRoutes(app) // เรียกใช้ Function ที่จะกำหนด Routes ทั้งหมดจาก internal/routes/routes.go
	slog.Info("API routes registered")

	// --- 7. Graceful Shutdown Setup ---
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	// --- 8. Start Server ---
	go func() {
		listenAddr := ":" + config.Env.Port
		slog.Info("Starting server...", "address", listenAddr)
		if err := app.Listen(listenAddr); err != nil && !errors.Is(err, http.ErrServerClosed) {
			slog.Error("Server failed to start", "error", err)
			quit <- syscall.SIGTERM // Trigger shutdown on listen error
		}
	}()

	// --- 9. Wait for Termination Signal ---
	sig := <-quit
	slog.Info("Received termination signal", "signal", sig.String())

	// --- 10. Perform Graceful Shutdown ---
	slog.Info("Shutting down server gracefully...", "timeout", config.Env.GracefulShutdownTimeout) // เพิ่ม Timeout ใน Config
	ctx, cancel := context.WithTimeout(context.Background(), config.Env.GracefulShutdownTimeout)
	defer cancel()

	if err := app.ShutdownWithContext(ctx); err != nil {
		slog.Error("Server shutdown failed", "error", err)
	}

	// --- 11. Close Database Connection Pool ---
	if dbInstance := database.GetDB(); dbInstance != nil {
		if sqlDB, err := dbInstance.DB(); err == nil {
			slog.Info("Closing database connection pool...")
			if err := sqlDB.Close(); err != nil {
				slog.Error("Failed to close database connections", "error", err)
			}
		}
	}

	slog.Info("Server exited gracefully")
}